//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asvn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asvn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Please, check that you have rights for the specified file..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write asvn -h for help..
        /// </summary>
        public static string AskForHelp {
            get {
                return ResourceManager.GetString("AskForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asvn error:.
        /// </summary>
        public static string AsvnError {
            get {
                return ResourceManager.GetString("AsvnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Ok.
        /// </summary>
        public static string ColonOk {
            get {
                return ResourceManager.GetString("ColonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conecting....
        /// </summary>
        public static string Conecting {
            get {
                return ResourceManager.GetString("Conecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database objects / database files must be the first in the collection.
        /// </summary>
        public static string DatabaseObjectMustBeFirst {
            get {
                return ResourceManager.GetString("DatabaseObjectMustBeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing response file at line {0}: {1}.
        /// </summary>
        public static string ErrorProcessingResponseFile {
            get {
                return ResourceManager.GetString("ErrorProcessingResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a valid command.
        /// </summary>
        public static string ExpectedValidCommand {
            get {
                return ResourceManager.GetString("ExpectedValidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0}.{1}.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for this object type.
        /// </summary>
        public static string ForThisObjectType {
            get {
                return ResourceManager.GetString("ForThisObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name &apos;{0}&apos; because do not exists or do not have access rights.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of options for command.
        /// </summary>
        public static string InvalidNumberOfOptions {
            get {
                return ResourceManager.GetString("InvalidNumberOfOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid accessObject name. Must be in &apos;xxx.name&apos; format. Where xxx is a valid object type..
        /// </summary>
        public static string InvalidObjectName {
            get {
                return ResourceManager.GetString("InvalidObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option &apos;{0}&apos;.
        /// </summary>
        public static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path for database or file do not exists.
        /// </summary>
        public static string InvalidPathForDatabase {
            get {
                return ResourceManager.GetString("InvalidPathForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path for output files do not exists.
        /// </summary>
        public static string OutputPathDoNotExist {
            get {
                return ResourceManager.GetString("OutputPathDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue.
        /// </summary>
        public static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type an object name per line (Enter an empty line for terminate)..
        /// </summary>
        public static string TypeObjectName {
            get {
                return ResourceManager.GetString("TypeObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///Main commands:
        ///  asvn [-general options] h[elp]|-? | i[import] | e[xport]
        ///Parameters for Import
        ///  [-options] databaseFile [file1 file2 ...|@responseFile]
        ///Parameters for Export
        ///  databaseFile exportFolder [*.*|objectname1 [objectname2 ...]|@resposeFile]
        ///
        ///General options
        /// -v                  Verbose: verbose output to stdout
        /// -w                  Wait: wait to any keystroke before end the program. Useful
        ///                     for interactive mode or for debugging
        /// 
        ///Commands:
        ///  h help -?     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
