//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessScrCtrlUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessScrCtrlUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async operation is already running.
        /// </summary>
        internal static string AsyncOperationAlreadyRunning {
            get {
                return ResourceManager.GetString("AsyncOperationAlreadyRunning", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon bas {
            get {
                object obj = ResourceManager.GetObject("bas", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dap {
            get {
                object obj = ResourceManager.GetObject("dap", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataAccessPages.
        /// </summary>
        internal static string DataAccessPagePlural {
            get {
                return ResourceManager.GetString("DataAccessPagePlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon db {
            get {
                object obj = ResourceManager.GetObject("db", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon dbp {
            get {
                object obj = ResourceManager.GetObject("dbp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string DefaultPlural {
            get {
                return ResourceManager.GetString("DefaultPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrams.
        /// </summary>
        internal static string DiagramPlural {
            get {
                return ResourceManager.GetString("DiagramPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No available files&gt;.
        /// </summary>
        internal static string EmptyFileStructure {
            get {
                return ResourceManager.GetString("EmptyFileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string FormPlural {
            get {
                return ResourceManager.GetString("FormPlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon frm {
            get {
                object obj = ResourceManager.GetObject("frm", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string FunctionPlural {
            get {
                return ResourceManager.GetString("FunctionPlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon lib {
            get {
                object obj = ResourceManager.GetObject("lib", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string Macro {
            get {
                return ResourceManager.GetString("Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macros.
        /// </summary>
        internal static string MacroPlural {
            get {
                return ResourceManager.GetString("MacroPlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon mcr {
            get {
                object obj = ResourceManager.GetObject("mcr", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ModulePlural {
            get {
                return ResourceManager.GetString("ModulePlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MSACCESS_258 {
            get {
                object obj = ResourceManager.GetObject("MSACCESS_258", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type not allowed for this type of Access file.
        /// </summary>
        internal static string NotAllowedObjectTypeException {
            get {
                return ResourceManager.GetString("NotAllowedObjectTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Database properties.dbp.txt&apos; file not found or is not valid..
        /// </summary>
        internal static string NotProjectType {
            get {
                return ResourceManager.GetString("NotProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertyPlural {
            get {
                return ResourceManager.GetString("PropertyPlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon qry {
            get {
                object obj = ResourceManager.GetObject("qry", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        internal static string QueryPlural {
            get {
                return ResourceManager.GetString("QueryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string ReferencePlural {
            get {
                return ResourceManager.GetString("ReferencePlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon rel {
            get {
                object obj = ResourceManager.GetObject("rel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportPlural {
            get {
                return ResourceManager.GetString("ReportPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folder do not exists or is invalid.
        /// </summary>
        internal static string RootPathNotValid {
            get {
                return ResourceManager.GetString("RootPathNotValid", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon rpt {
            get {
                object obj = ResourceManager.GetObject("rpt", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerView.
        /// </summary>
        internal static string ServerView {
            get {
                return ResourceManager.GetString("ServerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerViews.
        /// </summary>
        internal static string ServerViewPlural {
            get {
                return ResourceManager.GetString("ServerViewPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredProcedure.
        /// </summary>
        internal static string StoredProcedure {
            get {
                return ResourceManager.GetString("StoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredProcedures.
        /// </summary>
        internal static string StoredProcedurePlural {
            get {
                return ResourceManager.GetString("StoredProcedurePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string TablePlural {
            get {
                return ResourceManager.GetString("TablePlural", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon tbl {
            get {
                object obj = ResourceManager.GetObject("tbl", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
